import { readFileSync, writeFileSync } from 'node:fs';
import { isAbsolute, resolve } from 'node:path';

import type { Config } from '../util/config.js';
import { getPackageSpecificConfig, readConfig } from '../util/config.js';
import { createDatabase } from '../util/db.js';
import { getFileList, getRepoRoot } from '../util/files.js';
import { getPackageRootDirs } from '../util/getPackageRootDirs.js';
import { error, info, setVerbose, time } from '../util/logging.js';
import { printValidationErrors } from '../util/printValidationErrors.js';
import type {
  CommonOptions,
  LegacyComment,
  ValidationError,
} from '../util/types.js';
import { parseComments } from '../validate/parseComments.js';
import { addLegacyStatements } from './addLegacyStatements.js';
import { buildDatabase } from './buildDatabase.js';
import { parseResults } from './parseResults.js';
import { readResults } from './readResults.js';

export async function legacyExistingErrors(options: CommonOptions) {
  setVerbose(options.verbose);
  if (!isAbsolute(options.config)) {
    options.config = resolve(process.cwd(), options.config);
  }
  const config = readConfig(options.config);

  const repoRootDir = getRepoRoot(options.config);
  const legacyComments: LegacyComment[] = [];
  if (config.monorepoConfig) {
    const validationErrors: ValidationError[] = [];
    const packagePaths = getPackageRootDirs({
      repoRootDir,
      monorepoConfig: config.monorepoConfig,
      validationErrors,
    });
    if (validationErrors.length > 0) {
      error(
        `Invalid ignore package paths found while trying to legacy existing errors. Please fix the following errors and try again:`
      );
      printValidationErrors({ validationErrors, repoRootDir });
      process.exit(1);
    }
    for (const packageRootDir of packagePaths) {
      info(`Legacying errors in ${packageRootDir}...`);
      const packageSpecificConfig = getPackageSpecificConfig({
        packageRootDir,
        config,
      });
      const packageLegacyComments = await legacyPackage({
        config: packageSpecificConfig,
        repoRootDir,
        packageRootDir,
      });
      legacyComments.push(...packageLegacyComments);
    }
  } else {
    info(`Legacying errors...`);
    const packageLegacyComments = await legacyPackage({
      config,
      repoRootDir,
      packageRootDir: repoRootDir,
    });
    legacyComments.push(...packageLegacyComments);
  }

  time('creating database', () => {
    const validationErrors: ValidationError[] = [];
    const databaseContents = buildDatabase({
      legacyComments,
      validationErrors,
    });

    if (validationErrors.length > 0) {
      error(
        `Duplicate ID errors found while trying to build the new database. Please revert the changes from running the legacy command, ensure validation passes, and try again. If a duplicate ID was generated by the legacy command, then you're witnessing a 1 in a trillion event, which should not happen on the next run.`
      );
      printValidationErrors({ validationErrors, repoRootDir });
      process.exit(1);
    }

    const database = createDatabase({
      filePath: config.databaseFile,
      databaseContents,
    });
    database.save();
  });
}

async function legacyPackage({
  config: {
    lintCommand,
    linterType,
    ignoreWarnings,
    pragma,
    nonDisableableRules,
  },
  repoRootDir,
  packageRootDir,
}: {
  config: Config;
  repoRootDir: string;
  packageRootDir: string;
}) {
  const results = await time('reading results', () =>
    readResults({ lintCommand, linterType, packageRootDir })
  );
  const lintErrors = time('parsing results', () =>
    parseResults({ results, ignoreWarnings, linterType })
  );
  time('adding legacy statements', () => {
    for (const filePath of lintErrors.errors.keys()) {
      // Get comments so we can check if we need to add to an existing disable
      const fileContents = readFileSync(filePath, 'utf-8');
      const updatedFileContents = addLegacyStatements({
        pragma,
        lintErrors,
        fileContents,
        filePath,
        repoRootDir,
      });
      // Save the file if we have results to save. If we don't, that means there
      // was a malformed legacy comment and we should skip this file.
      if (updatedFileContents) {
        writeFileSync(filePath, updatedFileContents);
      }
    }
  });

  // Now we run steps that closely resemble validation. We do this to:
  // - Ensure there are no ID generation collisions (extremely rare)
  // - Make sure that no hand-edited changes slipped in before legacying
  //   that introduce duplicates, invalid rule sets on previous disables, etc.
  // - Get an updated list of IDs that properly mixes the new ones we just
  //   added with the ones from a previous run.
  // - Generate a composite database with the list of IDs and save it

  const files = time('getting file list', () => getFileList(packageRootDir));
  const validationErrors: ValidationError[] = [];
  const { legacyComments } = time('getting file comments', () =>
    parseComments({
      files,
      nonDisableableRules,
      validationErrors,
      pragma,
    })
  );

  if (validationErrors.length > 0) {
    error(
      `Parse errors found while trying to build the new database. This could happen because validation errors existed before the legacy command ran, which you will need to fix first. If running validation passes before running legacy but fails afterwards, there is likely a bug that should be reported to maintainers.`
    );
    printValidationErrors({ validationErrors, repoRootDir });
    process.exit(1);
  }

  return legacyComments;
}
